### ISSUE TITLE
Internal components

### ISSUE THREAD

**Issue by hypervtechnics** [hypervtechnics/jellyfin-mobile-native#7]
- [x] MVVM-Framework
- [x] Dependency Injection
- [x] Messagebus

**Comment by fruhnow** [comment]
Xamarin.Forms provides a build in Messagebus. We can just stick to this i guess.

https://docs.microsoft.com/de-de/xamarin/xamarin-forms/app-fundamentals/messaging-center

**Comment by hypervtechnics** [comment]
Yeah I stumbled over it during going through the generated project. Might read into the docs

**Comment by hypervtechnics** [comment]
Xamarin also provides an IoC Container I think

**Comment by hypervtechnics** [comment]
Message bus looks good. IoC does not support constructor injection. Can this be closed?
